# Generated by Django 4.0.6 on 2023-03-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIs',
            new_name='Product',
        ),
    ]
