# Generated by Django 4.0.6 on 2023-03-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_apis_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('img', models.ImageField(upload_to='Posted_Images')),
            ],
        ),
    ]
